server:
  port: 18081
  shutdown: graceful

kubernetes:
  config:
    namespace: datafabric
    argo-serviceaccount-name: default
    pvcName: datafabric-pvc
    podName: datafabric-pod
    mount-path: /mnt/df/

image:
  train-image-name: alpine:3.7
  inference-image-name: alpine:3.7
  downloader-image-name: 192.168.122.128:31234/ax_demo/downloader:0.1